import { sprintCalendar, shortDate, holiday } from './calendar.js';

const $ = id => document.getElementById(id);
const escape = value => String(value ?? '').replace(/[&<>"']/g, ch => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
const labels={PENDIENTE:'Pendiente',EN_DESARROLLO:'En desarrollo',PRUEBAS_MACAO:'Pruebas MACAO',VALIDACION_AFP:'Validación AFP',ACEPTADO:'Aceptado'};
const roleNames={ADMIN:'Coordinación',MACAO:'Equipo MACAO',AFP:'Validador AFP',CONSULTA:'Consulta'};
let data=null, currentUser=null, demo=false, view='dashboard', filters={search:'',sprint:'',owner:'',blocked:false,archived:false};
let loading=false, pendingRefresh=null, lastRefresh=null, modalTask=null, modalFocus=null;
let toastTimer;
function toast(message){$('toast').textContent=message;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').textContent='',5500);}
async function api(path, method='GET', body) {
  const headers={'X-Portal-Request':'1'};
  if(demo)headers['X-Demo-User']=sessionStorage.getItem('portal-demo-user')||'demo-admin';
  if(body!==undefined)headers['Content-Type']='application/json';
  const res=await fetch('/api/portal'+path,{method,headers,credentials:'same-origin',body:body===undefined?undefined:JSON.stringify(body)});
  const value=await res.json();
  if(!res.ok){if(res.status===401){currentUser=null;closeModal();login();}const error=new Error(value.message||'No se pudo completar la operación.');error.status=res.status;throw error;}
  return value;
}
const canEdit=()=>['ADMIN','MACAO'].includes(currentUser?.role);
const canComment=()=>currentUser?.role!=='CONSULTA';
const activeTasks=()=>data.tasks.filter(t=>!t.archived);
const person=id=>data.members.find(m=>m.id===id)?.name||'Sin asignar';
const dateTime=value=>new Date(value).toLocaleString('es-HN',{timeZone:'America/Tegucigalpa',dateStyle:'medium',timeStyle:'short'});
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/Tegucigalpa',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const weekDays=['lunes','martes','miércoles','jueves','viernes','sábado','domingo'];
const schedule=()=>sprintCalendar(data.project.startDate,data.project.morazanicaPause,data.project.virtualDay ?? 2);
const due=t=>t.dueDate||schedule().find(s=>s.sprint===t.sprint)?.saturday;
const overdue=t=>!t.archived&&t.status!=='ACEPTADO'&&due(t)&&due(t)<today();
function taskName(id){return data.tasks.find(t=>t.id===id)?.title||'Proyecto';}
function login(message='') {
  $('root').innerHTML=`<main class="login"><img src="/logo.png" alt="MACAO"><h1>Seguimiento del proyecto</h1><p>AFP Occidente · Motor de análisis y portal administrativo</p><form id="login-form"><label class="field">Usuario<input name="username" required autocomplete="username" maxlength="100"></label><label class="field">Contraseña<input name="password" type="password" required autocomplete="current-password" maxlength="200"></label><p class="error" id="login-error">${escape(message)}</p><button class="button" type="submit">Ingresar al portal</button></form></main>`;
  $('login-form').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),button=e.submitter;button.disabled=true;try{await api('/login','POST',Object.fromEntries(f));await boot();}catch(error){$('login-error').textContent=error.message;}finally{button.disabled=false;}};
}
async function boot(){try{const s=await api('/session');demo=s.demo;currentUser=s.user;if(demo){const selected=sessionStorage.getItem('portal-demo-user');if(selected)currentUser=(await api('/session')).user;}if(!currentUser)return login();await refresh(true);}catch(error){$('root').innerHTML=`<main class="login"><h1>Servicio no disponible</h1><p>${escape(error.message)}</p><button id="retry" class="button">Reintentar</button></main>`;$('retry').onclick=boot;}}
function shell(){
  const links=[['dashboard','Resumen del proyecto'],['scope','Propuesta y alcance'],['responsibilities','Responsabilidades'],['infrastructure','Infraestructura y Gemini'],['board','Muro de tareas'],['plan','Sprints y calendario'],['activity','Historial de cambios'],['team','Equipo y accesos']];
  $('root').innerHTML=`<div class="shell"><aside class="sidebar"><div class="brand"><img src="/logo.png" alt="MACAO"><span><b>AFP Occidente</b><small>Seguimiento del proyecto</small></span></div><div class="side-label">Espacio de trabajo</div><nav aria-label="Vistas del proyecto">${links.map(([id,title])=>`<button data-view="${id}" class="${view===id?'active':''}">${title}</button>`).join('')}</nav><div class="side-bottom">${demo?`<small>DEMO LOCAL · datos de prueba</small><select id="demo-user" aria-label="Perfil de demostración">${data.members.map(m=>`<option value="${m.id}" ${m.id===currentUser.id?'selected':''}>${escape(roleNames[m.role])}</option>`).join('')}</select>`:''}<span class="user-name">${escape(currentUser.name)}</span><small>${escape(roleNames[currentUser.role])}</small>${demo?'':'<button id="logout" class="link-button">Cerrar sesión</button>'}<div class="subtle">Portal v0.2.0<br>Tareas y comentarios compartidos</div></div></aside><div class="main"><header class="topbar"><div><strong>Motor de análisis y portal administrativo</strong><small>Propuesta v2.0 · MACAO Solutions y equipo IT del banco</small></div><img class="client-logo" src="/occidente.png" alt="AFP Occidente"><div><span class="pill ${demo?'warn':'ok'}">${demo?'Prueba local':'Acceso autenticado'}</span><small id="sync">${lastRefresh?'Actualizado '+lastRefresh.toLocaleTimeString('es-HN'):''}</small></div></header><main class="content" id="content" tabindex="-1"></main></div></div>`;
  document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;filters={search:'',sprint:'',owner:'',blocked:false,archived:false};render();});
  if($('demo-user'))$('demo-user').onchange=async e=>{sessionStorage.setItem('portal-demo-user',e.target.value);closeModal();await refresh(true);};
  if($('logout'))$('logout').onclick=async()=>{await api('/logout','POST',{});currentUser=null;login();};
}
async function refresh(full=false){
  if(loading){await pendingRefresh;return refresh(full);}loading=true;
  try{pendingRefresh=api('/project');data=await pendingRefresh;currentUser=data.user;lastRefresh=new Date();if(full||!$('content'))render();else if(!$('task-dialog').open){paint();$('sync').textContent='Actualizado '+lastRefresh.toLocaleTimeString('es-HN');}}
  catch(error){toast(error.message);}finally{loading=false;}
}
function render(){shell();paint();}
function heading(title,description,actions=''){return `<div class="page-title"><div><h1>${title}</h1><p>${description}</p></div><div class="toolbar">${actions}</div></div>`;}
function paint(){
  const methods={dashboard,scope,responsibilities,infrastructure,board,plan,activity,team};$('content').innerHTML=methods[view]();bindCommon();
  document.querySelectorAll('[data-proposal-view]').forEach(b=>b.onclick=()=>{view=b.dataset.proposalView;render();});
  if(view==='board')bindFilters();if(view==='plan')bindSettings();if(view==='team')bindTeam();
}
function metrics(){
  const tasks=activeTasks().filter(t=>t.kind!=='SOLICITUD'),deliverables=tasks.filter(t=>t.kind==='ENTREGABLE'),accepted=deliverables.filter(t=>t.status==='ACEPTADO').length;
  return `<div class="metrics"><div class="metric"><strong>${accepted} / ${deliverables.length}</strong><span>Entregables aceptados</span><small>Validación por AFP o coordinación</small></div><div class="metric"><strong>${tasks.filter(t=>t.status==='VALIDACION_AFP').length}</strong><span>En validación AFP</span><small>Pendientes de decisión</small></div><div class="metric"><strong>${tasks.filter(t=>t.blocked).length}</strong><span>Tareas bloqueadas</span><small>Con causa registrada</small></div><div class="metric"><strong>${tasks.filter(overdue).length}</strong><span>Tareas vencidas</span><small>${data.project.startDate?'Fecha propia o revisión de sprint':'Solo tareas con fecha propia'}</small></div></div>`;
}
function sprintCards(){return `<div class="sprint-grid">${data.sprints.map((s,i)=>{const tasks=activeTasks().filter(t=>t.sprint===i+1&&t.kind!=='SOLICITUD'),done=tasks.filter(t=>t.status==='ACEPTADO').length;const date=schedule().find(x=>x.sprint===i+1);return `<button class="sprint-card" data-sprint="${i+1}"><span class="eyebrow">Sprint ${i+1}</span><h3>${escape(s[0])}</h3><small>${shortDate(date?.start)}${date?.end?' – '+shortDate(date.end):''}</small><progress class="progress" max="${Math.max(tasks.length,1)}" value="${done}">${done}/${tasks.length}</progress><small>${done} de ${tasks.length} tareas aceptadas</small></button>`;}).join('')}</div>`;}
function dashboard(){
  const active=schedule().find(s=>s.start&&s.start<=today()&&s.end>=today()),blocks=activeTasks().filter(t=>t.blocked||overdue(t));
  return heading('Resumen del proyecto','Entregables, decisiones y trabajo compartido.',`<button class="button secondary" data-refresh>Actualizar</button>`)+`<section class="hero"><div><span class="eyebrow">${!data.project.startDate?'Inicio por acordar':active?.sprint?'Sprint '+active.sprint:active?'Pausa programada':'Calendario definido'}</span><h2>Motor de análisis y portal administrativo.</h2><p>${!data.project.startDate?'MACAO desarrolla el motor y su portal. IT integra APEX y habilita los servicios del banco. Definamos el calendario y los responsables para comenzar.':active?.sprint?escape(data.sprints[active.sprint-1][1]):'Consulta los sprints y las tareas pendientes para coordinar el trabajo.'}</p></div><button class="button" data-open-board>Abrir muro de tareas →</button></section>`+proposalSummary()+metrics()+`<h2>Avance por sprint</h2>`+sprintCards()+`<div class="grid2"><section class="panel"><h2>Requieren atención</h2>${blocks.length?blocks.slice(0,8).map(t=>`<div class="list-row"><span><button class="link-button" data-task="${t.id}">${escape(t.title)}</button><small>${escape(t.blocked||'Fecha objetivo vencida')}</small></span><span class="pill warn">${t.blocked?'Bloqueo':'Vencida'}</span></div>`).join(''):'<p class="empty">Sin bloqueos ni vencimientos registrados.</p>'}</section><section class="panel"><h2>Últimos movimientos</h2>${data.events.slice(0,5).map(e=>`<div class="list-row"><span>${escape(e.action)}<small>${escape(e.actorName)} · ${escape(taskName(e.taskId))}</small></span><small>${escape(dateTime(e.at))}</small></div>`).join('')||'<p class="empty">El historial comienza con la primera actualización.</p>'}</section></div>`+holidayNote();
}
function filteredTasks(){return data.tasks.filter(t=>t.archived===filters.archived&&(!filters.sprint||t.sprint===Number(filters.sprint))&&(!filters.owner||t.assigneeId===filters.owner)&&(!filters.blocked||t.blocked)&&(!filters.search||(t.title+' '+t.description).toLocaleLowerCase().includes(filters.search.toLocaleLowerCase())));}
function card(t){return `<button class="task-card" data-task="${t.id}"><span class="eyebrow">S${t.sprint} · ${t.kind==='SOLICITUD'?'Solicitud':t.kind==='ENTREGABLE'?'Entregable':'Tarea'}</span><h3>${escape(t.title)}</h3><small>${escape(person(t.assigneeId))}</small><div class="meta"><span class="pill ${t.blocked||overdue(t)?'warn':''}">${t.blocked?'Bloqueada':overdue(t)?'Vencida':t.priority}</span><small>${shortDate(due(t))}</small></div></button>`;}
function board(){
  return heading('Muro de tareas','Abre una tarjeta para actualizarla, comentar o validar.',`${canEdit()?'<button class="button" data-new>Nueva tarea +</button>':''}<button class="button secondary" id="export-csv">Exportar CSV</button>`)+`<div class="filters"><input id="search" aria-label="Buscar tarea" placeholder="Buscar tareas…" value="${escape(filters.search)}"><select id="sprint-filter" aria-label="Filtrar sprint"><option value="">Todos los sprints</option>${data.sprints.map((_,i)=>`<option value="${i+1}" ${String(i+1)===filters.sprint?'selected':''}>Sprint ${i+1}</option>`).join('')}</select><select id="owner-filter" aria-label="Filtrar responsable"><option value="">Todos los responsables</option>${data.members.map(m=>`<option value="${m.id}" ${filters.owner===m.id?'selected':''}>${escape(m.name)}</option>`).join('')}</select><label><input id="blocked-filter" type="checkbox" ${filters.blocked?'checked':''}>Bloqueadas</label><label><input id="archive-filter" type="checkbox" ${filters.archived?'checked':''}>Archivadas</label></div><div id="board-columns">${columns()}</div><p class="board-note">Las solicitudes de cambio se registran aparte del avance comprometido. Coordinación debe incorporarlas al alcance antes de aceptarlas. Todos los comentarios son visibles para AFP.</p>`;
}
function columns(){const tasks=filteredTasks();return `<div class="board">${Object.entries(labels).map(([status,name])=>`<section class="column"><div class="column-head"><span>${name}</span><span>${tasks.filter(t=>t.status===status).length}</span></div>${tasks.filter(t=>t.status===status).map(card).join('')||'<p class="empty">Sin tareas</p>'}</section>`).join('')}</div>`;}
function bindFilters(){
  const update=()=>{$('board-columns').innerHTML=columns();bindTasks();};
  $('search').oninput=e=>{filters.search=e.target.value;update();};
  $('sprint-filter').onchange=e=>{filters.sprint=e.target.value;update();};
  $('owner-filter').onchange=e=>{filters.owner=e.target.value;update();};
  $('blocked-filter').onchange=e=>{filters.blocked=e.target.checked;update();};
  $('archive-filter').onchange=e=>{filters.archived=e.target.checked;update();};
  $('export-csv').onclick=()=>{const cell=v=>'"'+String(v??'').replace(/^[=+@\-\t\r]/,"'$&").replaceAll('"','""')+'"';const rows=[['Título','Sprint','Estado','Responsable','Tipo','Fecha objetivo','Bloqueo'],...filteredTasks().map(t=>[t.title,t.sprint,labels[t.status],person(t.assigneeId),t.kind,due(t),t.blocked])];download('tareas-afp.csv','\uFEFF'+rows.map(r=>r.map(cell).join(',')).join('\r\n'),'text/csv;charset=utf-8');};
}
function download(name,content,type){const a=document.createElement('a'),url=URL.createObjectURL(new Blob([content],{type}));a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),2000);}
function holidayNote(){return `<section class="holiday"><strong>Semana Morazánica 2026</strong><p>Feriado privado del 7 de octubre a las 12:00 al 10 de octubre a las 12:00. La pausa completa del 5 al 11 es una propuesta de organización; requiere acuerdo. No habrá revisión presencial el sábado 10. El 15 de septiembre también reduce la capacidad del sprint correspondiente.</p><p><a href="https://www.hondudiario.com/2026/08/24/cohep-confirma-feriados-del-15-de-septiembre-y-semana-morazanica-para-el-sector-privado/" target="_blank" rel="noopener noreferrer">Referencia del comunicado de COHEP</a> · Otros feriados y cierres deben verificarse. Calendario de referencia 2026.</p></section>`;}
function plan(project=data.project){const cols=sprintCalendar(project.startDate,project.morazanicaPause,project.virtualDay ?? 2);return heading('Sprints y calendario','Ocho sprints de trabajo. El calendario compartido se modifica mediante un acuerdo.',`<button class="button secondary" id="print-plan">Imprimir</button>`)+`<div class="table-wrap"><table class="gantt"><thead><tr><th>Entregable</th>${cols.map(c=>`<th class="${c.sprint?'':'paused'}">${c.sprint?'Sprint '+c.sprint:'Pausa Morazánica'}<small>${shortDate(c.start)}${c.end?' – '+shortDate(c.end):''}</small></th>`).join('')}</tr></thead><tbody>${data.sprints.map((s,i)=>`<tr><td>${escape(s[0])}</td>${cols.map(c=>`<td class="${c.sprint?'':'paused'}">${c.sprint===i+1?`<button data-sprint="${i+1}">Ver S${i+1}</button>`:c.sprint?'':'—'}</td>`).join('')}</tr>`).join('')}<tr><td>Virtual · ${weekDays[project.virtualDay ?? 2]}</td>${cols.map(c=>`<td>${c.sprint?c.virtual?holiday(c.virtual)||shortDate(c.virtual):'Por acordar':'Sin sesión'}</td>`).join('')}</tr><tr><td>Revisión · sábado</td>${cols.map(c=>`<td>${c.sprint?c.saturday?holiday(c.saturday)||shortDate(c.saturday):'Por acordar':'Sin sesión'}</td>`).join('')}</tr></tbody></table></div><p class="note">${project.startDate?`Ocho sprints en ${cols.length} semanas calendario. Fin estimado: ${shortDate(cols.at(-1).end)}. `:'Fecha de inicio por acordar. '}Meta: piloto integrado en S6 y entrega completa en S8. Se incluye una sesión técnica semanal con IT de hasta 60 minutos, con horario por acordar. La validación de tareas no sustituye la aceptación final contractual. ${project.startDate&&!project.startDate.startsWith('2026')?'Atención: los feriados precargados corresponden únicamente a 2026.':''}</p>${currentUser.role==='ADMIN'?`<section class="panel"><h2>Actualizar calendario compartido</h2><form id="settings-form"><div class="form-grid"><label class="field">Fecha de inicio — lunes<input name="startDate" type="date" value="${escape(project.startDate)}"></label><label class="field">Día de reunión virtual<select name="virtualDay">${weekDays.map((day,i)=>`<option value="${i}" ${i===(project.virtualDay ?? 2)?'selected':''}>${day}</option>`).join('')}</select></label><label class="field">Pausa Morazánica propuesta<select name="morazanicaPause"><option value="yes" ${project.morazanicaPause?'selected':''}>Pausar del 5 al 11 de octubre de 2026</option><option value="no" ${!project.morazanicaPause?'selected':''}>Mantener sprint con capacidad reducida</option></select></label><label class="field wide">Acuerdo o motivo del ajuste<textarea name="reason" required maxlength="2000" placeholder="Registrar quiénes acordaron el calendario y el motivo del cambio"></textarea></label></div><p class="error" id="settings-error"></p><div class="form-actions"><button class="button" type="submit">Guardar calendario</button></div></form></section>`:''}`+holidayNote();}
function bindSettings(){if($('print-plan'))$('print-plan').onclick=()=>window.print();const form=$('settings-form');if(form){const version=data.project.settingsVersion;form.onchange=()=>{try{const f=Object.fromEntries(new FormData(form));const preview=document.createElement('template');preview.innerHTML=plan({...data.project,startDate:f.startDate||null,virtualDay:Number(f.virtualDay),morazanicaPause:f.morazanicaPause==='yes'});document.querySelector('.table-wrap').replaceWith(preview.content.querySelector('.table-wrap'));document.querySelector('.content > .note').replaceWith(preview.content.querySelector('.note'));$('settings-error').textContent='Vista previa: guarda el calendario para compartir estos cambios.';bindCommon();}catch(error){$('settings-error').textContent=error.message;}};form.onsubmit=e=>submit(e,'settings-error',async()=>{const f=Object.fromEntries(new FormData(form));await api('/settings','PATCH',{...f,startDate:f.startDate||null,morazanicaPause:f.morazanicaPause==='yes',virtualDay:Number(f.virtualDay),version});await refresh(true);toast('Calendario guardado para el equipo.');});}}
function activity(){return heading('Historial de cambios','Últimos 500 movimientos. Hora de Honduras; los registros se conservan en el servidor.')+`<section class="panel">${data.events.map(e=>`<article class="history-entry"><strong>${escape(e.action)}</strong> · ${escape(e.actorName)}<small>${escape(dateTime(e.at))} · ${escape(taskName(e.taskId))}</small><p>${escape(e.detail)}</p>${e.taskId?`<button class="link-button" data-task="${e.taskId}">Ver tarea</button>`:''}</article>`).join('')||'<p class="empty">Todavía no hay cambios registrados.</p>'}</section>`;}
function team(){return heading('Equipo y accesos','Cuentas independientes del sistema de afiliaciones.')+`<section class="panel"><div class="table-wrap"><table><thead><tr><th>Nombre</th><th>Usuario</th><th>Perfil</th><th>Acceso</th><th></th></tr></thead><tbody>${data.members.map(m=>`<tr><td>${escape(m.name)}</td><td>${escape(m.username)}</td><td>${roleNames[m.role]}</td><td>${m.active?'Activo':'Inactivo'}</td><td>${currentUser.role==='ADMIN'&&!demo?`<button class="link-button" data-member="${m.id}">Administrar</button>`:''}</td></tr>`).join('')}</tbody></table></div><p class="note">Coordinación administra el plan; MACAO ejecuta tareas; AFP valida o devuelve; Consulta solo visualiza. Los enlaces de evidencia no cambian los permisos del repositorio donde estén alojados.</p></section>${demo?'<p class="note">La demo incluye cuatro perfiles de prueba. No se crean contraseñas ni cuentas reales aquí.</p>':currentUser.role==='ADMIN'?`<section class="panel section-line"><h2>Crear cuenta</h2><form id="member-form"><div class="form-grid"><label class="field">Nombre<input name="name" required maxlength="120"></label><label class="field">Usuario<input name="username" required maxlength="100" autocomplete="off"></label><label class="field">Perfil<select name="role">${Object.entries(roleNames).map(([id,name])=>`<option value="${id}" ${id==='CONSULTA'?'selected':''}>${name}</option>`).join('')}</select></label><label class="field">Contraseña inicial<input name="password" type="password" required minlength="12" maxlength="200" autocomplete="new-password"></label></div><p class="error" id="member-error"></p><div class="form-actions"><button class="button">Crear cuenta</button></div></form></section>`:''}`;}
function bindTeam(){if($('member-form'))$('member-form').onsubmit=e=>submit(e,'member-error',async()=>{await api('/members','POST',Object.fromEntries(new FormData(e.target)));await refresh(true);toast('Cuenta creada.');});document.querySelectorAll('[data-member]').forEach(b=>b.onclick=()=>openMember(b.dataset.member));}
function openMember(id){const m=data.members.find(x=>x.id===id);showModal(`<h2 id="task-heading">Acceso de ${escape(m.name)}</h2>`,`<form id="member-edit"><div class="form-grid"><label class="field">Perfil<select name="role">${Object.entries(roleNames).map(([id,name])=>`<option value="${id}" ${id===m.role?'selected':''}>${name}</option>`).join('')}</select></label><label class="field">Estado<select name="active"><option value="yes" ${m.active?'selected':''}>Activo</option><option value="no" ${!m.active?'selected':''}>Inactivo</option></select></label><label class="field wide">Nueva contraseña — opcional<input name="password" type="password" minlength="12" maxlength="200" autocomplete="new-password"></label></div><p class="note">Guardar revoca las sesiones de esta cuenta.</p><p class="error" id="member-edit-error"></p><div class="form-actions"><button class="button">Guardar acceso</button></div></form>`);$('member-edit').onsubmit=e=>submit(e,'member-edit-error',async()=>{const f=Object.fromEntries(new FormData(e.target));await api('/members/'+id,'PATCH',{...f,active:f.active==='yes'});closeModal();await refresh(true);toast('Acceso actualizado.');});}
function bindTasks(){document.querySelectorAll('[data-task]').forEach(b=>b.onclick=()=>openTask(b.dataset.task));}
function bindCommon(){bindTasks();document.querySelectorAll('[data-sprint]').forEach(b=>b.onclick=()=>{view='board';filters.sprint=b.dataset.sprint;render();});document.querySelectorAll('[data-new]').forEach(b=>b.onclick=()=>openTask(null));document.querySelectorAll('[data-refresh]').forEach(b=>b.onclick=()=>refresh(true));document.querySelectorAll('[data-open-board]').forEach(b=>b.onclick=()=>{view='board';render();});}
async function submit(e,errorId,operation){e.preventDefault();const button=e.submitter;const target=$(errorId);if(target)target.textContent='';if(button)button.disabled=true;try{await operation();}catch(error){if($(errorId))$(errorId).textContent=error.message;else toast(error.message);}finally{if(button)button.disabled=false;}}
function showModal(title,content){modalFocus=document.activeElement;$('task-dialog').innerHTML=`<header class="modal-head">${title}<button class="close" id="close-modal" aria-label="Cerrar detalle">×</button></header><div class="modal-body">${content}</div>`;$('close-modal').onclick=closeModal;if(!$('task-dialog').open)$('task-dialog').showModal();}
function closeModal(){if($('task-dialog').open)$('task-dialog').close();modalTask=null;if(modalFocus?.isConnected)modalFocus.focus();}
$('task-dialog').addEventListener('cancel',()=>{modalTask=null;});
function taskForm(t){const selected=t?.dependencies||[];return `<form id="task-form"><div class="form-grid"><label class="field wide">Título<input name="title" required maxlength="160" value="${escape(t?.title)}"></label><label class="field wide">Descripción<textarea name="description" maxlength="4000">${escape(t?.description)}</textarea></label><label class="field wide">Criterio de aceptación<textarea name="acceptance" required maxlength="2000">${escape(t?.acceptance)}</textarea></label><label class="field">Sprint<select name="sprint">${data.sprints.map((_,i)=>`<option value="${i+1}" ${i+1===(t?.sprint||Number(filters.sprint)||1)?'selected':''}>Sprint ${i+1}</option>`).join('')}</select></label><label class="field">Responsable<select name="assigneeId"><option value="">Sin asignar</option>${data.members.filter(m=>m.active&&m.role!=='CONSULTA').map(m=>`<option value="${m.id}" ${t?.assigneeId===m.id?'selected':''}>${escape(m.name)}</option>`).join('')}</select></label><label class="field">Prioridad<select name="priority">${['ALTA','MEDIA','BAJA'].map(v=>`<option ${v===(t?.priority||'MEDIA')?'selected':''}>${v}</option>`).join('')}</select></label><label class="field">Tipo<select name="kind">${['TAREA','ENTREGABLE','SOLICITUD'].map(v=>`<option ${v===(t?.kind||'TAREA')?'selected':''}>${v}</option>`).join('')}</select></label><label class="field">Fecha objetivo — opcional<input name="dueDate" type="date" value="${escape(t?.dueDate)}"></label><label class="field">Evidencia — enlace<input name="evidence" type="url" maxlength="2000" placeholder="https://…" value="${escape(t?.evidence)}"></label><label class="field wide">Depende de — selección múltiple<select name="dependencies" multiple size="4">${data.tasks.filter(x=>!x.archived&&x.id!==t?.id).map(x=>`<option value="${x.id}" ${selected.includes(x.id)?'selected':''}>S${x.sprint} · ${escape(x.title)}</option>`).join('')}</select><small>Usa Ctrl o ⌘ para elegir varias. La aceptación requiere dependencias aceptadas.</small></label></div><p class="error" id="task-error"></p><div class="form-actions"><button class="button" type="submit">${t?'Guardar cambios':'Crear tarea'}</button></div></form>`;}
function openTask(id){
  const t=id?data.tasks.find(x=>x.id===id):null;if(id&&!t)return toast('Tarea no encontrada.');
  modalTask=t?structuredClone(t):null;
  const editable=canEdit()&&!t?.archived&&t?.status!=='ACEPTADO';
  const read=t?`<dl class="readonly"><dt>Descripción</dt><dd>${escape(t.description)||'Sin descripción'}</dd><dt>Criterio de aceptación</dt><dd>${escape(t.acceptance)}</dd><dt>Responsable</dt><dd>${escape(person(t.assigneeId))}</dd><dt>Fecha objetivo</dt><dd>${shortDate(due(t))}</dd><dt>Dependencias</dt><dd>${escape(t.dependencies.map(taskName).join(', '))||'Sin dependencias'}</dd><dt>Evidencia</dt><dd>${t.evidence?`<a href="${escape(t.evidence)}" target="_blank" rel="noopener noreferrer">Abrir evidencia ↗</a>`:'Pendiente'}</dd></dl>`:'';
  const comments=t?data.comments.filter(c=>c.taskId===t.id):[];
  showModal(`<div><span class="eyebrow">${t?'Sprint '+t.sprint+' · '+labels[t.status]:'Nueva tarea'}${t?.archived?' · Archivada':''}</span><h2 id="task-heading">${escape(t?.title||'Registrar trabajo')}</h2></div>`,t?`<div class="task-layout"><section>${editable?taskForm(t):read}</section><section>${t.evidence&&editable?`<a class="link-button" href="${escape(t.evidence)}" target="_blank" rel="noopener noreferrer">Abrir evidencia registrada ↗</a>`:''}${!t.archived&&canComment()?actions(t):''}<div class="section-line"><h3>Comentarios compartidos</h3><div class="thread">${comments.map(c=>`<article class="comment"><strong>${escape(c.actorName)}</strong><small>${escape(dateTime(c.at))}</small><p>${escape(c.text)}</p></article>`).join('')||'<p class="empty">Sin comentarios todavía.</p>'}</div>${canComment()&&!t.archived?'<form id="comment-form"><label class="field">Añadir comentario<textarea name="text" required maxlength="4000" placeholder="Observación visible para MACAO y AFP"></textarea></label><p class="error" id="comment-error"></p><div class="form-actions"><button class="button secondary">Publicar comentario</button></div></form>':''}</div><div class="section-line"><h3>Historial de esta tarea</h3>${data.events.filter(e=>e.taskId===t.id).slice(0,12).map(e=>`<article class="comment"><strong>${escape(e.action)}</strong><small>${escape(e.actorName)} · ${escape(dateTime(e.at))}</small><p>${escape(e.detail)}</p></article>`).join('')||'<p class="empty">Sin cambios registrados.</p>'}</div></section></div>`:taskForm(null));
  if($('task-form'))$('task-form').onsubmit=e=>submit(e,'task-error',async()=>{const form=new FormData(e.target),b=Object.fromEntries(form);b.sprint=Number(b.sprint);b.assigneeId=b.assigneeId||null;b.dueDate=b.dueDate||null;b.dependencies=form.getAll('dependencies');if(t)b.version=modalTask.version;const result=await api('/tasks'+(t?'/'+t.id:''),t?'PATCH':'POST',b);await refresh();openTask(result.id);toast(t?'Cambios guardados.':'Tarea creada.');});
  if($('comment-form'))$('comment-form').onsubmit=e=>submit(e,'comment-error',async()=>{await api('/tasks/'+t.id+'/comments','POST',Object.fromEntries(new FormData(e.target)));await refresh();openTask(t.id);toast('Comentario registrado.');});
  if(t)bindTaskActions(t);
  if(t?.archived&&currentUser.role==='ADMIN'){
    const form=document.createElement('form');form.className='section-line';form.innerHTML='<label class="field">Restaurar tarea<input name="reason" required maxlength="2000" placeholder="Motivo de la restauración"></label><p class="error" id="restore-error"></p><div class="form-actions"><button class="button secondary">Restaurar tarea</button></div>';
    $('task-dialog').querySelector('.modal-body').append(form);
    form.onsubmit=e=>submit(e,'restore-error',async()=>{await api('/tasks/'+t.id+'/restore','POST',{...Object.fromEntries(new FormData(form)),version:modalTask.version});await refresh();closeModal();paint();toast('Tarea restaurada.');});
  }
}
function actions(t){let targets=[];const index=Object.keys(labels).indexOf(t.status);
  if(currentUser.role==='AFP'){if(t.status==='VALIDACION_AFP')targets=['ACEPTADO','PRUEBAS_MACAO'];}
  else if(t.status==='ACEPTADO'){if(currentUser.role==='ADMIN')targets=['PRUEBAS_MACAO'];}
  else{targets=Object.keys(labels).filter((s,i)=>i<=index+1&&s!==t.status&&(s!=='ACEPTADO'||currentUser.role==='ADMIN'));}
  return `<h3>Estado y seguimiento</h3>${t.blocked?`<p class="error">Bloqueo: ${escape(t.blocked)}</p>`:''}${targets.length?`<form id="status-form"><div class="inline-form"><select name="status" aria-label="Nuevo estado">${targets.map(s=>`<option value="${s}" ${s===Object.keys(labels)[index+1]?'selected':''}>${labels[s]}</option>`).join('')}</select></div><label class="field">Observación de transición<textarea name="note" maxlength="2000" placeholder="Obligatoria para aceptar, devolver o reabrir"></textarea></label><p class="error" id="status-error"></p><div class="form-actions"><button class="button secondary">Actualizar estado</button></div></form>`:''}${t.status!=='ACEPTADO'?`<form id="block-form" class="section-line"><label class="field">${t.blocked?'Resolver o actualizar bloqueo':'Registrar bloqueo'}<input name="reason" maxlength="2000" value="${escape(t.blocked)}" placeholder="Causa y acción necesaria"></label><small>Para resolver, deja la razón vacía y guarda.</small><p class="error" id="block-error"></p><div class="form-actions"><button class="button secondary">Guardar bloqueo</button></div></form>`:''}${currentUser.role==='ADMIN'?`<form id="archive-form" class="section-line"><label class="field">Archivar tarea<input name="reason" required maxlength="2000" placeholder="Motivo obligatorio"></label><small>Conserva el historial y retira la tarea del avance activo.</small><p class="error" id="archive-error"></p><div class="form-actions"><button class="button secondary">Archivar</button></div></form>`:''}`;}
function bindTaskActions(t){for(const action of ['status','block','archive']){const form=$(action+'-form');if(form)form.onsubmit=e=>submit(e,action+'-error',async()=>{const b=Object.fromEntries(new FormData(form));b.version=modalTask.version;await api('/tasks/'+t.id+'/'+action,'POST',b);await refresh();if(action==='archive'){closeModal();paint();}else openTask(t.id);toast('Actualización registrada.');});}}
setInterval(()=>{if(currentUser&&!$('task-dialog').open&&!document.querySelector('form')&&!document.querySelector('.filters:focus-within'))void refresh();},30000);
window.addEventListener('focus',()=>{if(currentUser&&!$('task-dialog').open&&!document.querySelector('form'))void refresh();});
void boot();

function money(value){return 'L '+Number(value).toLocaleString('en-US');}
function proposalSummary(){return `<section class="proposal-summary" aria-label="Condiciones de la propuesta"><div><span class="eyebrow">Propuesta v${escape(data.proposal.version)}</span><strong>${money(data.proposal.amount)} <small>más ISV</small></strong></div><div><b>8 semanas</b><small>Piloto integrado en S6 · entrega en S8</small></div><div><b>${escape(data.proposal.model)}</b><small>Infraestructura y consumo a cargo del banco</small></div><button class="button secondary" data-proposal-view="scope">Ver alcance</button></section>`;}
function infoTable(headers,rows){return `<div class="table-wrap"><table class="proposal-table"><thead><tr>${headers.map(x=>`<th scope="col">${escape(x)}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr>${row.map(x=>`<td>${escape(x)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;}
function bulletList(items){return `<ul class="scope-list">${items.map(x=>`<li>${escape(x)}</li>`).join('')}</ul>`;}
function scope(){const p=data.proposal;return heading('Propuesta y alcance','Versión 2.0 · trabajo conjunto MACAO, IT y AFP Occidente.')+proposalSummary()+`<div class="grid2"><section class="panel"><h2>MACAO desarrolla</h2>${bulletList(p.scope)}</section><section class="panel"><h2>El banco aporta y desarrolla</h2>${bulletList(p.bankScope)}</section></div><h2 class="section-title">Inversión y pagos</h2>`+infoTable(['Concepto','Base','Total con ISV'],[['Desarrollo e implementación',money(p.amount),money(p.total)],['Anticipo 50%',money(p.payment),money(p.paymentTotal)],['Aceptación final 50%',money(p.payment),money(p.paymentTotal)]])+`<p class="note">ISV de la propuesta: 15%. No representa pagos registrados. Inicio sujeto a acta, anticipo y prerrequisitos. Ocho semanas de ejecución; cualquier pausa acordada puede extender el calendario.</p><h2 class="section-title">Criterios de aceptación</h2>`+infoTable(['Frente','Evidencia esperada'],p.acceptance)+`<p class="note">La administración permite ajustar las reglas soportadas; nuevas familias de validación o integraciones requieren control de cambios. No se incluye alojamiento AWS. La aprobación de expedientes permanece en personal autorizado.</p>`;}
function responsibilities(){return heading('Matriz de responsabilidades','Funciones por equipo. Los responsables nominales de las tareas se asignan en el muro.')+infoTable(['Actividad','MACAO','IT del banco','AFP y responsables de negocio'],data.proposal.responsibilities)+`<section class="panel section-title"><h2>Coordinación compartida</h2><p>AFP designa un responsable de producto que consolide decisiones y aceptación. Cada equipo desarrolla, prueba y corrige su componente; la integración se valida de extremo a extremo.</p><p class="note">Una reunión de seguimiento y una sesión técnica con IT cada semana, ambas de hasta 60 minutos. Hasta ocho revisiones presenciales de sábado, de hasta tres horas. Decisiones ordinarias en dos días hábiles; bloqueos registrados con responsable, impacto y fecha.</p></section>`;}
function infrastructure(){const p=data.proposal;return heading('Infraestructura y Gemini','Recursos provistos y administrados por el banco; MACAO instala e integra su solución.')+`<section class="panel model-panel"><span class="eyebrow">Modelo requerido</span><h2>${escape(p.model)}</h2><code>${escape(p.modelId)}</code><p class="note">${escape(p.modelContinuity)}</p></section><h2 class="section-title">Requerimientos iniciales</h2>`+infoTable(['Recurso','Requerimiento propuesto'],p.infrastructure)+`<p class="note">Dimensionamiento provisional, sujeto a volumen, páginas, concurrencia y retención. No se prevé GPU. El banco habilita facturación, cuotas, credenciales y salida HTTPS hacia Gemini; una suscripción de chat no sustituye el acceso por API.</p><section class="panel"><h2>Datos y puesta en operación</h2><p>El contenido enviado a Gemini se procesa en el servicio externo autorizado, aunque el motor opere en el servidor local del banco. El acta técnica debe definir autorizaciones, retención, respaldos y recuperación antes de producción.</p></section>`;}
